music_directory    "/home/myka/music/"
playlist_directory "/home/myka/.config/mpd/playlists"
db_file            "/home/myka/.config/mpd/database"

audio_output {
        type            "pipewire" 
        name            "PipeWire Sound Server"
}
