# Enable opacity
inactive-opacity = 0.80
active-opacity = 1.0
inactive-opacity-override = false

# Exclude specific apps from opacity change
opacity-rule = [
  "100:class_g = 'Chromium'",
  "100:class_g = 'rofi'",
  "100:class_g = 'obsidian'"
];

# Other common settings
backend = "glx";
vsync = true;

# Shadows
shadow = true
shadow-radius = 12
shadow-offset-x = -7
shadow-offset-y = -7
shadow-opacity = 0.7
shadow-exclude = [
  "class_g = 'Conky'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
]

# Backend
backend = "glx"
vsync = true

# Optional: fading animations
fading = true
fade-delta = 4

# rounded
rounded-corners = true;
corner-radius = 6; 

