[colors]
background = #282A2E
background-alt = #373B41
foreground = #C5C8C6
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880

[bar/example]
width = 100%
height = 24pt
radius = 6

; dpi = 96
background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

; space in module
padding-left = 0
padding-right = 1

; space between modules
module-margin = 1

; separator between modules
separator = |
separator-foreground = ${colors.disabled}

; font-0 = monospace;2
; font-1 = Font Awesome 6 Free:size=10;0

font-0 = "FiraCode Nerd Font:size=10;0"
font-1 = "Noto Color Emoji:size=10;1"  

; modules for left and right
modules-left = xworkspaces xwindow
modules-right = wifi battery-combined-tlp pulseaudio popup-calendar 

; change a cursor when cursor is on clickable bar
cursor-click = pointer
cursor-scroll = ns-resize

; enable interaction of polybar with external scripts
enable-ipc = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = ●
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = ●
label-occupied-padding = 1

label-urgent = ●
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = ●
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

; the name of current window running
[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

; calendar
[module/popup-calendar]
type = custom/script
exec = ~/.config/polybar/scripts/popup-calendar.sh
interval = 5
click-left = ~/.config/polybar/scripts/popup-calendar.sh --popup &

; battery
[module/battery-combined-tlp]
type = custom/script
exec = ~/.config/polybar/scripts/battery-combined-tlp.sh
interval = 3

[module/pulseaudio]
type = internal/pulseaudio
 
format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/wifi]
type = custom/script
exec = ~/.config/polybar/scripts/wifi_show.sh 
interval = 3
click-left = ~/.config/polybar/scripts/wifi_click.sh 

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini

